-- Enable Stripe integration
-- create extension if not exists wrappers with schema extensions;
-- create foreign data wrapper stripe_wrapper
--   handler stripe_fdw_handler
--   validator stripe_fdw_validator;
--
-- create server stripe_server
--   foreign data wrapper stripe_wrapper
--   options (
--     api_key_name 'stripe'
--   );
--
-- create schema stripe;
--
-- -- Stripe customers table
-- create foreign table stripe.customers (
--   id text,
--   email text,
--   name text,
--   description text,
--   created timestamp,
--   attrs jsonb
-- )
-- server stripe_server
-- options (
--   object 'customers',
--   rowid_column 'id'
-- );
